remove hard-coded in defining number of fields and fix errbit error (#1292)
fix number of bullet to save article values by removing hard coded
fix TypeError: "a.replaceAll is not a function" by using "replace" function instead of "replaceAll" as this method is available in Node versions 15 and up and the current version we are using Node v12.16.1.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility

Reference: CHECK-2723