Adding Ngrok token to Travis job (similarity tests)
We use Ngrok for the similarity integration tests. Now, a token is required. This PR is to fix this error that is currently being displayed on CI:

```
ERROR:  authentication failed: Usage of ngrok requires a verified account and authtoken.
ERROR:  
ERROR:  Sign up for an account: https://dashboard.ngrok.com/signup
ERROR:  Install your authtoken: https://dashboard.ngrok.com/get-started/your-authtoken
ERROR:  
ERROR:  ERR_NGROK_4018
ERROR: 
```

The token was added directly to Travis and is available as a secret constant NGROK_AUTH.